packages:
  - apps/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - cpu-features
  - esbuild
  - maplibre-gl
  - protobufjs
  - sharp
  - ssh2
  - unrs-resolver
  - vue-demi
