name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'Image/VERSION'

env:
  REPO: open-rcoder-worker
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Read version from file
      id: version
      run: echo "VERSION=$(cat Image/VERSION | tr -d '\n')" >> $GITHUB_OUTPUT

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Check if version already exists
      run: |
        if docker manifest inspect "${{ env.REGISTRY }}/${{ github.repository_owner }}/${REPO,,}:${{ steps.version.outputs.VERSION }}" > /dev/null 2>&1; then
          echo "Version ${{ steps.version.outputs.VERSION }} already exists in registry"
          exit 1
        fi
        
    - name: Build Docker image with version tag
      run: docker build Image --file Image/Dockerfile --tag "${{ env.REGISTRY }}/${{ github.repository_owner }}/${REPO,,}:${{ steps.version.outputs.VERSION }}"
        
    - name: Build Docker image with latest tag
      run: docker build Image --file Image/Dockerfile --tag "${{ env.REGISTRY }}/${{ github.repository_owner }}/${REPO,,}:latest"
        
    - name: Push version tag
      run: docker push "${{ env.REGISTRY }}/${{ github.repository_owner }}/${REPO,,}:${{ steps.version.outputs.VERSION }}"
        
    - name: Push latest tag
      run: docker push "${{ env.REGISTRY }}/${{ github.repository_owner }}/${REPO,,}:latest"